http://localhost:3000/cadastrados

###

POST http://localhost:3000/cadastrados HTTP/1.1
content-type: application/json

{
    "nome": "Bruno",
    "idade": 18,
    "escolaridade": "Ensino Médio Completo"
}